version: "3.9"

services:
  backend:
    image: xmax11/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo

  frontend:
    image: xmax11/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
