name: Docker Build and Push to EC2
on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
      - name: Build and push frontend 
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      - name: Build and push mongo
        uses: docker/build-push-action@v2
        with:
          context: ./mongo
          file: ./mongo/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/mongo:latest
      - name: Deploy to AWS EC2
        uses: aws-actions/amazon-ec2-deploy-ssh-key@v2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/mongo:latest
            docker-compose up -d
   
